# Generated by Django 5.2.14 on 2026-05-12 20:57

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='слаг')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, validators=[apps.accounts.validators.validate_belarus_mobile_phone], verbose_name='телефон')),
                ('address', models.TextField(verbose_name='адрес')),
                ('contract_number', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='номер договора')),
                ('medications', models.ManyToManyField(blank=True, related_name='suppliers', to='pharmacy.medication', verbose_name='препараты')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['slug'], name='suppliers_s_slug_ab1d61_idx'), models.Index(fields=['name'], name='suppliers_s_name_6277a9_idx'), models.Index(fields=['email'], name='suppliers_s_email_971388_idx'), models.Index(fields=['contract_number'], name='suppliers_s_contrac_110073_idx')],
            },
        ),
    ]
