# Generated by Django 5.2.14 on 2026-05-12 21:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('COMPLETED', 'Проведена'), ('CANCELLED', 'Отменена')], db_index=True, default='COMPLETED', max_length=20, verbose_name='статус')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='сумма')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_as_customer', to=settings.AUTH_USER_MODEL, verbose_name='покупатель')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_as_employee', to=settings.AUTH_USER_MODEL, verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'продажа',
                'verbose_name_plural': 'продажи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='цена за единицу')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='сумма строки')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='pharmacy.medication', verbose_name='препарат')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='продажа')),
            ],
            options={
                'verbose_name': 'строка продажи',
                'verbose_name_plural': 'строки продаж',
                'ordering': ('pk',),
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-created_at', 'status'], name='sales_sale_created_9452e1_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer', '-created_at'], name='sales_sale_custome_a89379_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['employee', '-created_at'], name='sales_sale_employe_a21b30_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'medication'], name='sales_salei_sale_id_9bbd9e_idx'),
        ),
    ]
