# Generated by Codex on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=models.CharField(default="Europe/Moscow", max_length=64, verbose_name="часовой пояс"),
        ),
    ]
