# Generated by Django 5.2.14 on 2026-05-22 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='слаг')),
                ('position', models.CharField(max_length=255, verbose_name='должность')),
                ('photo', models.ImageField(upload_to='employees/%Y/%m/', verbose_name='фотография')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('work_calendar', models.TextField(verbose_name='текстовый календарь')),
                ('note', models.TextField(blank=True, verbose_name='информация')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100, verbose_name='порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='показывать на сайте')),
            ],
            options={
                'verbose_name': 'контакт сотрудника',
                'verbose_name_plural': 'контакты сотрудников',
                'ordering': ('sort_order', 'full_name'),
                'indexes': [models.Index(fields=['is_active', 'sort_order', 'full_name'], name='core_employ_is_acti_f60fbf_idx'), models.Index(fields=['slug'], name='core_employ_slug_45fcc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='слаг')),
                ('image', models.ImageField(upload_to='news/%Y/%m/', verbose_name='изображение')),
                ('lead', models.TextField(verbose_name='анонс')),
                ('content', models.TextField(verbose_name='текст новости')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ('-published_at', '-created_at'),
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='core_newsar_is_publ_bc1454_idx'), models.Index(fields=['slug'], name='core_newsar_slug_faf14c_idx'), models.Index(fields=['title'], name='core_newsar_title_d6532e_idx')],
            },
        ),
    ]
