# Generated by Django 5.2.14 on 2026-09-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyinfo_banner_glossaryterm_partner_promocode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='certificate_image',
            field=models.ImageField(blank=True, help_text='Скан или фотография. Если загружено — показывается вместо текста.', upload_to='company/', verbose_name='фото сертификата'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='certificate_image_alt',
            field=models.CharField(blank=True, help_text='Что изображено — читается скринридером вместо картинки.', max_length=255, verbose_name='описание фото сертификата'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='certificate_text',
            field=models.TextField(blank=True, help_text='Показывается, если фото не загружено; иначе доступен как расшифровка.', verbose_name='текст сертификата'),
        ),
    ]
