# Generated by Django 5.2.14 on 2026-05-12 20:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='слаг')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['slug'], name='pharmacy_ca_slug_d1ac18_idx'), models.Index(fields=['name'], name='pharmacy_ca_name_8c2fd7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='слаг')),
                ('floor', models.SmallIntegerField(verbose_name='этаж')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'отдел',
                'verbose_name_plural': 'отделы',
                'ordering': ('floor', 'name'),
                'indexes': [models.Index(fields=['slug'], name='pharmacy_de_slug_8572d2_idx'), models.Index(fields=['name'], name='pharmacy_de_name_d2d1af_idx'), models.Index(fields=['floor'], name='pharmacy_de_floor_35d373_idx')],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='слаг')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('instruction', models.TextField(blank=True, verbose_name='инструкция')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='производитель')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='остаток')),
                ('expiration_date', models.DateField(verbose_name='срок годности')),
                ('requires_prescription', models.BooleanField(default=False, verbose_name='рецепт обязателен')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medications/%Y/%m/', verbose_name='изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='pharmacy.category', verbose_name='категория')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='pharmacy.department', verbose_name='отдел')),
            ],
            options={
                'verbose_name': 'препарат',
                'verbose_name_plural': 'препараты',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['slug'], name='pharmacy_me_slug_db6238_idx'), models.Index(fields=['name'], name='pharmacy_me_name_46a660_idx'), models.Index(fields=['code'], name='pharmacy_me_code_f924c9_idx'), models.Index(fields=['expiration_date'], name='pharmacy_me_expirat_fae540_idx'), models.Index(fields=['requires_prescription'], name='pharmacy_me_require_21dba2_idx'), models.Index(fields=['category', 'department'], name='pharmacy_me_categor_f35bc6_idx'), models.Index(fields=['price'], name='pharmacy_me_price_0868ca_idx')],
            },
        ),
    ]
